/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAtaRouteImport } from './routes/_authenticated/ata'
import { Route as AuthenticatedClimaRouteImport } from './routes/_authenticated/clima'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipamentosRouteImport } from './routes/_authenticated/equipamentos'
import { Route as AuthenticatedInformesRouteImport } from './routes/_authenticated/informes'
import { Route as AuthenticatedInformeIdRouteImport } from './routes/_authenticated/informe.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtaRoute = AuthenticatedAtaRouteImport.update({
  id: '/ata',
  path: '/ata',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClimaRoute = AuthenticatedClimaRouteImport.update({
  id: '/clima',
  path: '/clima',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipamentosRoute =
  AuthenticatedEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformesRoute = AuthenticatedInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInformeIdRoute = AuthenticatedInformeIdRouteImport.update({
  id: '/informe/$id',
  path: '/informe/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/ata': typeof AuthenticatedAtaRoute
  '/clima': typeof AuthenticatedClimaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/informe/$id': typeof AuthenticatedInformeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/ata': typeof AuthenticatedAtaRoute
  '/clima': typeof AuthenticatedClimaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/informe/$id': typeof AuthenticatedInformeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/ata': typeof AuthenticatedAtaRoute
  '/_authenticated/clima': typeof AuthenticatedClimaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/_authenticated/informes': typeof AuthenticatedInformesRoute
  '/_authenticated/informe/$id': typeof AuthenticatedInformeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistente'
    | '/ata'
    | '/clima'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/informes'
    | '/informe/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assistente'
    | '/ata'
    | '/clima'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/informes'
    | '/informe/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistente'
    | '/_authenticated/ata'
    | '/_authenticated/clima'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipamentos'
    | '/_authenticated/informes'
    | '/_authenticated/informe/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ata': {
      id: '/_authenticated/ata'
      path: '/ata'
      fullPath: '/ata'
      preLoaderRoute: typeof AuthenticatedAtaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clima': {
      id: '/_authenticated/clima'
      path: '/clima'
      fullPath: '/clima'
      preLoaderRoute: typeof AuthenticatedClimaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos': {
      id: '/_authenticated/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AuthenticatedEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes': {
      id: '/_authenticated/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof AuthenticatedInformesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informe/$id': {
      id: '/_authenticated/informe/$id'
      path: '/informe/$id'
      fullPath: '/informe/$id'
      preLoaderRoute: typeof AuthenticatedInformeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedAtaRoute: typeof AuthenticatedAtaRoute
  AuthenticatedClimaRoute: typeof AuthenticatedClimaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipamentosRoute: typeof AuthenticatedEquipamentosRoute
  AuthenticatedInformesRoute: typeof AuthenticatedInformesRoute
  AuthenticatedInformeIdRoute: typeof AuthenticatedInformeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedAtaRoute: AuthenticatedAtaRoute,
  AuthenticatedClimaRoute: AuthenticatedClimaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipamentosRoute: AuthenticatedEquipamentosRoute,
  AuthenticatedInformesRoute: AuthenticatedInformesRoute,
  AuthenticatedInformeIdRoute: AuthenticatedInformeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
